apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parchment-keeweb
  namespace: argocd
spec:
  project: parchment
  destination:
    server: "https://kubernetes.default.svc"
    namespace: parchment-keeweb
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://ldtteam.github.io/keeweb
      chart: keeweb
      targetRevision: "1.*"
      helm:
        releaseName: parchment-keeweb
        valuesObject:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: letsencrypt-parchment
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              external-dns.alpha.kubernetes.io/target: "cluster.ldtteam.com."
            hosts:
              - keeweb.parchmentmc.net
              - keeweb.parchmentmc.org
          autoscaling:
            enabled: true


