apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parchment-keeweb-storage
  namespace: argocd
spec:
  project: parchment
  destination:
    server: "https://kubernetes.default.svc"
    namespace: parchment-keeweb-storage
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://ldtteam.github.io/NginxWebDav/
      chart: nginx-web-dav
      targetRevision: "0.*"
      helm:
        releaseName: parchment-keeweb-storage
        valuesObject:
          persistence:
            labels:
              recurring-job-group.longhorn.io/high-frequency: "enabled"
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: letsencrypt-parchment
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              external-dns.alpha.kubernetes.io/target: "cluster.ldtteam.com."
            hosts:
              - fileshare-new.parchmentmc.net
              - fileshare-new.parchmentmc.org
            auth:
              enabled: true
              secretRef:
                name: keeweb-auth
              realm: "Parchment FileShare"
          autoscaling:
            enabled: true