---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: storage-credentials
  namespace: parchment-keeweb-storage
spec:
  encryptedData:
    auth: AgCew50kNGRQFZcLEJTnLH0GxqVoC9vBqJP2i/k1w+8D3DnEUeeO2/p/S+lBg8OhvFR8C6TgFv0afzki5kchIT4NEPMTAvmSPkI/DA3maNH+k6TMDHyW80tDdVFsgN9BxZR3QFrz0vGT6DESVUlDxtHmYg0P4TiBkcu96koo9U+EZh9LW8GE6juAdIcmTYIuz6rVTdBSstX/5WhWeJEO/6l4DDZo5xXhLz/HjSZKYbKUZJYbPtRJgB47wHhbmIS98AuIhCU71MaFlnpSi2n0AznX+MhAP6ZVfZAbBVU+Xk4PkTslrYGKxI/w/wVaqbS2/W+U9oj1BaugcI+ndSf+4JxV/YoyvBv7c3dI1sPf90CI5XqlAhAmw2Qf1cBodnKAQNPt3eTgUPaU7ULIzWLXTqTdUBt4r+iOf/5aeOS0H7Hp5dG20c/v4AIRajPVsz+R4v2/dezMPRCinNLwOhtK2iBKmNP0e2I7E3SgmHWWPPBlPK5kATs3NyIkTHEWgMvpOCX2NNG7HFQWLa5ZY0XHaPlYtF7ktejzbqiHwt/po97sCF4ccCzqTWXBxuSPswmv57nUqSEomCQRspyJbsmX94AtHC/OFMGDoDwZ8GiUgq0taHDgsLnSOah6pgeBEor0YdVDh0FYvugT4GiHJA5uiE8o4ODWRUo0a4Wk4G0HeA0FK7dqEYh8cbBLBWjQDMoVwKwVymoiRTwRt6lIljjEbQ/4jAxyo29VoY+YFjbrGNpd9YdbmyR9iBe1e1xvb2GkaNTb5vla
  template:
    metadata:
      name: storage-credentials
      namespace: parchment-keeweb-storage
      labels:
        app.kubernetes.io/part-of: parchment-keeweb-storage
