apiVersion: v1
kind: Service
metadata:
  name: parchment-maven
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: ldtteam.jfrog.io
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP